### ISSUE TITLE
TeamSpeak3-Client-linux_amd64-3.2.1.run did not pass valididty check

### ISSUE THREAD

**Issue by Pillgar** [frebib/teamspeak3-bin#1]
Validating source files with sha512sums failed on TeamSpeak3-Client-linux_amd64-3.2.1.run.

teamspeak3.desktop ... Passed
teamspeak3.png ... Passed
LICENSE ... Passed
TeamSpeak3-Client-linux_amd64-3.2.1.run ... FAILED

passing --skipchecksums installs without issue.  Just a heads up.  Ty for maintaining this!!!!

**Comment by frebib** [comment]
Welp shit. It's either my fault or they changed the checksum, I'm not sure. Go ahead and build it with --skip-checksums, or update the checksum in the PKGBUILD. I'll fix this tomorrow, thanks for pointing it out

**Comment by Pillgar** [comment]
yup, works great BTW.  TY frebib!!!

**Comment by frebib** [comment]
Fixed in https://github.com/frebib/teamspeak3-bin/commit/35559144a634abcbaa39a4737f7c58c90787c87e
