### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by Pillgar** [frebib/teamspeak3-bin#2]
I tried to open Teamspeak today and nothing happened.  So I decided to download and install it again.  Though i recieve the following error when running makepkg command:

==> Validating source files with sha512sums...
    teamspeak3.desktop ... Passed
    teamspeak3.png ... Passed
    LICENSE ... Passed
    TeamSpeak3-Client-linux_amd64-3.2.3.run ... FAILED
==> ERROR: One or more files did not pass the validity check!

when I use the --skipchecksums for the pkgbuild, I get:

==> Extracting sources...
==> Starting prepare()...
chmod: missing operand after ‘644’
Try 'chmod --help' for more information.
==> ERROR: A failure occurred in prepare().
    Aborting...

Not sure if this an isolated issue on my end, but I thought I'd bring it to your attention just in case.

All the best.

**Comment by frebib** [comment]
No it's likely because this is relying upon a particular version. I can try to fix this but I've had to stop using it because of TS incompatibility :/

**Comment by frebib** [comment]
Building for the latest version `3.2.3` gives me this error:
```
frebib@frebib-PC ~/p/f/teamspeak3-bin> teamspeak3                                                                                           
teamspeak3: relocation error: teamspeak3: symbol calloc version Qt_5 not defined in file libQt5WebEngineCore.so.5 with link time reference
```

**Comment by frebib** [comment]
Fixed again with a newer TS3 client version
